"""empty message

Revision ID: 4f7fc3ddbf40
Revises: e895da8ee487
Create Date: 2023-07-11 21:32:29.886570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7fc3ddbf40'
down_revision = 'e895da8ee487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=True),
    sa.Column('inspect_date', sa.DateTime(), nullable=False),
    sa.Column('queen', sa.String(), nullable=True),
    sa.Column('health', sa.String(), nullable=True),
    sa.Column('temperment', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hive_id'], ['hive.hive_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('hive', 'temperment')
    op.drop_column('hive', 'health')
    op.drop_column('hive', 'queen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hive', sa.Column('queen', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hive', sa.Column('health', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hive', sa.Column('temperment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('inspection')
    # ### end Alembic commands ###
